import type { CapabilityDefinition, CapabilityId } from './types';

export const COGNITIVE_CAPABILITIES: Record<CapabilityId, CapabilityDefinition> = {
  'lexis-rules': {
    id: 'lexis-rules',
    label: 'Lexis Rules',
    description: 'Regras determinísticas de carteira, permissões, CNJ, prazos e dados.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['W2CAPITAL/LexisPredict'],
  },
  'memory-v2': {
    id: 'memory-v2',
    label: 'Memória v2',
    description: 'Recuperação lexical, compactação e deduplicação antes de chamar modelo.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['ItsWambarYT/ai-brain', 'thedotmack/claude-mem', 'mycelium-hq/ai-brain-starter'],
  },
  council: {
    id: 'council',
    label: 'Council X',
    description: 'Análise por lentes independentes e síntese com terceira perspectiva.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['obra/superpowers', 'affaan-m/ECC', 'alphaXiv/OpenResearch'],
  },
  research: {
    id: 'research',
    label: 'Research Agent',
    description: 'Decompõe pesquisa, exige evidência e mantém rastreabilidade das fontes.',
    runtime: 'server',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['SamurAIGPT/llm-wiki-agent', 'alphaXiv/OpenResearch', 'D4Vinci/Scrapling'],
  },
  'browser-agent': {
    id: 'browser-agent',
    label: 'Browser Agent',
    description: 'Automação de navegador isolada e observável para tarefas autorizadas.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['ChromeDevTools/chrome-devtools-mcp', 'D4Vinci/Scrapling', 'tinyhumansai/openhuman'],
  },
  'change-watch': {
    id: 'change-watch',
    label: 'Change Watch',
    description: 'Detecção de mudanças com snapshot, diff e debounce.',
    runtime: 'server',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['dgtlmoon/changedetection.io', 'tj/watch'],
  },
  ocr: {
    id: 'ocr',
    label: 'OCR Multimotor',
    description: 'PaddleOCR self-host quando disponível, com fallback local Tesseract.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['PaddlePaddle/PaddleOCR'],
  },
  'document-understanding': {
    id: 'document-understanding',
    label: 'Document Understanding',
    description: 'Extrai, normaliza e estrutura documentos antes de raciocínio jurídico.',
    runtime: 'server',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['PaddlePaddle/PaddleOCR', 'hugohe3/ppt-master'],
  },
  'report-engine': {
    id: 'report-engine',
    label: 'Report Engine',
    description: 'Gera relatórios com evidência, seções reutilizáveis e validação.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['hugohe3/ppt-master', 'affaan-m/ECC'],
  },
  'presentation-engine': {
    id: 'presentation-engine',
    label: 'Presentation Engine',
    description: 'Planeja narrativa e slides a partir de dados estruturados.',
    runtime: 'server',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['hugohe3/ppt-master'],
  },
  'voice-studio': {
    id: 'voice-studio',
    label: 'Voice Studio',
    description: 'Adapter opcional para síntese e edição de voz, fora do bundle principal.',
    runtime: 'sidecar',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['debpalash/VoiceStudio'],
  },
  'image-enhance': {
    id: 'image-enhance',
    label: 'Image Enhance',
    description: 'Upscale/limpeza visual por worker opcional, sem carregar modelos no Vercel.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['upscayl/upscayl'],
  },
  'visual-render': {
    id: 'visual-render',
    label: 'Visual Render',
    description: 'Pipeline opcional para render e estilização, isolado do núcleo jurídico.',
    runtime: 'sidecar',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['ssloy/tinyrenderer', 'TachibanaYoshino/AnimeGANv3', 'dtoyoda10/anime-gen'],
  },
  'model-cascade': {
    id: 'model-cascade',
    label: 'Model Cascade',
    description: 'Cascata existente de modelos; usada somente depois das camadas determinísticas.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['tinyhumansai/openhuman', 'earendil-works/pi', 'pacifio/atlas'],
  },
  'quality-gate': {
    id: 'quality-gate',
    label: 'Quality Gate',
    description: 'Verifica completude, evidência, contradições e saída antes da entrega.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['affaan-m/ECC', 'obra/superpowers'],
  },
  observability: {
    id: 'observability',
    label: 'Agent Observability',
    description: 'Registra intenção, plano, motor, latência e falhas sem guardar segredos.',
    runtime: 'server',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['playbox-dev/trackstudio', 'ruvnet/RuView'],
  },
};

export function listCapabilities(): CapabilityDefinition[] {
  return Object.values(COGNITIVE_CAPABILITIES);
}
