import type { CapabilityDefinition, CapabilityId } from './types';

export const COGNITIVE_CAPABILITIES: Record<CapabilityId, CapabilityDefinition> = {
  'lexis-rules': {
    id: 'lexis-rules',
    label: 'Lexis Rules',
    description: 'Regras determinísticas de carteira, permissões, CNJ, prazos e dados.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['W2CAPITAL/LexisPredict'],
  },
  'memory-v2': {
    id: 'memory-v2',
    label: 'Memória v2',
    description: 'Recuperação lexical, compactação e deduplicação antes de chamar modelo.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['ItsWambarYT/ai-brain', 'thedotmack/claude-mem', 'mycelium-hq/ai-brain-starter'],
  },
  council: {
    id: 'council',
    label: 'Council X',
    description: 'Análise por lentes independentes e síntese com terceira perspectiva.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['obra/superpowers', 'affaan-m/ECC', 'alphaXiv/OpenResearch'],
  },
  research: {
    id: 'research',
    label: 'Research Agent',
    description: 'Decompõe pesquisa, exige evidência e mantém rastreabilidade das fontes.',
    runtime: 'server',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['SamurAIGPT/llm-wiki-agent', 'alphaXiv/OpenResearch', 'D4Vinci/Scrapling'],
  },
  'browser-agent': {
    id: 'browser-agent',
    label: 'Browser Agent',
    description: 'Automação de navegador isolada e observável para tarefas autorizadas.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['ChromeDevTools/chrome-devtools-mcp', 'D4Vinci/Scrapling', 'tinyhumansai/openhuman'],
  },
  'change-watch': {
    id: 'change-watch',
    label: 'Change Watch',
    description: 'Detecção de mudanças com snapshot, diff e debounce.',
    runtime: 'server',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['dgtlmoon/changedetection.io', 'tj/watch'],
  },
  ocr: {
    id: 'ocr',
    label: 'OCR Multimotor',
    description: 'PaddleOCR self-host quando disponível, com fallback local Tesseract.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['PaddlePaddle/PaddleOCR'],
  },
  'document-understanding': {
    id: 'document-understanding',
    label: 'Document Understanding',
    description: 'Extrai, normaliza e estrutura documentos antes de raciocínio jurídico.',
    runtime: 'server',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['PaddlePaddle/PaddleOCR', 'hugohe3/ppt-master'],
  },
  'report-engine': {
    id: 'report-engine',
    label: 'Report Engine',
    description: 'Gera relatórios com evidência, seções reutilizáveis e validação.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['hugohe3/ppt-master', 'affaan-m/ECC'],
  },
  'presentation-engine': {
    id: 'presentation-engine',
    label: 'Presentation Engine',
    description: 'Planeja narrativa e slides a partir de dados estruturados.',
    runtime: 'server',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['hugohe3/ppt-master'],
  },
  'voice-studio': {
    id: 'voice-studio',
    label: 'Voice Studio',
    description: 'Adapter opcional para síntese e edição de voz, fora do bundle principal.',
    runtime: 'sidecar',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['debpalash/VoiceStudio'],
  },
  'image-enhance': {
    id: 'image-enhance',
    label: 'Image Enhance',
    description: 'Upscale/limpeza visual por worker opcional, sem carregar modelos no Vercel.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['upscayl/upscayl'],
  },
  'visual-render': {
    id: 'visual-render',
    label: 'Visual Render',
    description: 'Pipeline opcional para render e estilização, isolado do núcleo jurídico.',
    runtime: 'sidecar',
    zeroToken: false,
    optional: true,
    sourcePatterns: ['ssloy/tinyrenderer', 'TachibanaYoshino/AnimeGANv3', 'dtoyoda10/anime-gen'],
  },
  'model-cascade': {
    id: 'model-cascade',
    label: 'Model Cascade',
    description: 'Cascata existente de modelos; usada somente depois das camadas determinísticas.',
    runtime: 'server',
    zeroToken: false,
    optional: false,
    sourcePatterns: ['tinyhumansai/openhuman', 'earendil-works/pi', 'pacifio/atlas'],
  },
  'quality-gate': {
    id: 'quality-gate',
    label: 'Quality Gate',
    description: 'Verifica completude, evidência, contradições e saída antes da entrega.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['affaan-m/ECC', 'obra/superpowers'],
  },
  firecrawl: {
    id: 'firecrawl',
    label: 'Firecrawl Web Data',
    description: 'Pesquisa e extração web estruturada via cloud ou instância self-host.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['firecrawl/firecrawl', 'D4Vinci/Scrapling'],
  },
  'simulation-engine': {
    id: 'simulation-engine',
    label: 'Scenario Simulator',
    description: 'Monte Carlo local e determinístico para comparar cenários sob incerteza.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['nikmcfly/MiroFish-Offline', 'xcontcom/neuroparticles'],
  },
  'skill-library': {
    id: 'skill-library',
    label: 'Skill & Learning Library',
    description: 'Catálogo curado para aprender padrões sem instalar código automaticamente.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['mattpocock/skills', 'codecrafters-io/build-your-own-x', 'freeCodeCamp/freeCodeCamp', 'sindresorhus/awesome'],
  },
  'api-discovery': {
    id: 'api-discovery',
    label: 'API Discovery',
    description: 'Descoberta orientada de APIs públicas com revisão de autenticação, termos e segurança.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['public-apis/public-apis', 'sindresorhus/awesome'],
  },
  'comfy-media': {
    id: 'comfy-media',
    label: 'ComfyUI Media Engine',
    description: 'Workflows opcionais de imagem e vídeo em ComfyUI, fora do bundle Vercel.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['Comfy-Org/ComfyUI', 'upscayl/upscayl', 'TachibanaYoshino/AnimeGANv3'],
  },
  'plugin-platform': {
    id: 'plugin-platform',
    label: 'Plugin Platform',
    description: 'Registry, permissões e executores allowlisted para capacidades internas e sidecars.',
    runtime: 'server',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['TransformerOptimus/SuperAGI', 'zernio-dev/zernio-claude-plugin', 'screenpipe/screenpipe'],
  },
  'world-sandbox': {
    id: 'world-sandbox',
    label: 'World Sandbox',
    description: 'Mundo procedural por chunks, biomas, recursos e agentes com seed reproduzível.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['fogleman/Craft', 'dgreenheck/minecraft-threejs-clone', '0xfabian/mc', 'kwai/DouZero'],
  },
  'agent-studio': {
    id: 'agent-studio',
    label: 'Agent Studio',
    description: 'Planejamento de equipes de agentes especializados, ferramentas e gates.',
    runtime: 'inline',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['Donchitos/Claude-Code-Game-Studios', 'TransformerOptimus/SuperAGI', 'reworkd/AgentGPT'],
  },
  'screen-context': {
    id: 'screen-context',
    label: 'Screen Context',
    description: 'Contexto local opcional de tela/áudio fornecido pelo próprio usuário.',
    runtime: 'sidecar',
    zeroToken: true,
    optional: true,
    sourcePatterns: ['screenpipe/screenpipe'],
  },
  observability: {
    id: 'observability',
    label: 'Agent Observability',
    description: 'Registra intenção, plano, motor, latência e falhas sem guardar segredos.',
    runtime: 'server',
    zeroToken: true,
    optional: false,
    sourcePatterns: ['pacifio/atlas', 'affaan-m/ECC', 'alphaXiv/OpenResearch'],
  },
};

export function listCapabilities(): CapabilityDefinition[] {
  return Object.values(COGNITIVE_CAPABILITIES);
}
