-- Fix operational writes for the commercial tenant.
-- Additive only: no user/business rows are removed.

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='processos'
      and column_name='id'
      and is_identity='NO'
      and column_default is null
  ) then
    alter table public.processos
      alter column id add generated by default as identity;
  end if;
end $$;

alter table public.clientes_operacao
  add column if not exists cliente text,
  add column if not exists banco text,
  add column if not exists protocolo text,
  add column if not exists dados jsonb not null default '{}'::jsonb,
  add column if not exists created_by uuid,
  add column if not exists edited_by_name text,
  add column if not exists updated_at timestamptz not null default now();

update public.clientes_operacao
set cliente = coalesce(cliente, nome)
where cliente is null and nome is not null;

create index if not exists idx_clientes_operacao_empresa_tipo
  on public.clientes_operacao(empresa_id, tipo);

create index if not exists idx_clientes_operacao_empresa_cliente
  on public.clientes_operacao(empresa_id, cliente);

create or replace function public.current_empresa_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select u.empresa_id
  from public.usuarios u
  where u.auth_user_id = auth.uid()
  limit 1
$$;

revoke all on function public.current_empresa_id() from public;
grant execute on function public.current_empresa_id() to authenticated;

do $$
declare
  t text;
begin
  foreach t in array array[
    'processos',
    'clientes_operacao',
    'crm_tarefas',
    'crm_negocios',
    'crm_atividades',
    'notes'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists %I on public.%I', t || '_tenant_select', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (empresa_id = public.current_empresa_id())',
      t || '_tenant_select', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_tenant_insert', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (empresa_id = public.current_empresa_id())',
      t || '_tenant_insert', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_tenant_update', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using (empresa_id = public.current_empresa_id()) with check (empresa_id = public.current_empresa_id())',
      t || '_tenant_update', t
    );

    execute format('drop policy if exists %I on public.%I', t || '_tenant_delete', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated using (empresa_id = public.current_empresa_id())',
      t || '_tenant_delete', t
    );
  end loop;
end $$;
